[package]
name = "rust_2023_25"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.6"
ndarray-npy = "0.8.1"
numpy = "0.20.0"
pyo3 = "0.20.0"
relative-path = "1.9.2"
